services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: appdb
  backend:
    build:
      context: backend/Linquiztic
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    depends_on:
      - db
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - VITE_AI_KEY=${VITE_API_KEY}
        
    ports:
      - "80:80"
    depends_on:
      - backend
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    # env_file:
    #   - .env

